### ISSUE TITLE
Convert questions of validation data to form fields

### ISSUE THREAD

**Issue by ericvdbergeFontys** [BonsAI-Group/Text-to-case#21]

**Comment by vcaf** [comment]
- match label to question context

**Comment by vcaf** [comment]
![Image](https://user-images.githubusercontent.com/78371221/225858085-08c78f07-41b0-417d-a725-c56d8e04a550.png)

Preview of the labels for the lunch request form with description

**Comment by vcaf** [comment]
![Image](https://user-images.githubusercontent.com/78371221/225858257-9db51d37-c24c-4314-99c2-a2fb0a7eb87c.png)

Preview of the labels for the security incident form with description
