### ISSUE TITLE
Scope

### ISSUE THREAD

**Issue by ericvdbergeFontys** [BonsAI-Group/Text-to-case#4]

**Comment by Eliturbo** [comment]
Money limitation
Knowledge limitation

Table (inside scope: deployable, outside scope: azure)

**Comment by Eliturbo** [comment]
Introduction

**Comment by Eliturbo** [comment]
Introduction to requirements

**Comment by vcaf** [comment]
Rewording "the solution must be GDPR compliant" to something similar that we are GDPR aware.
